feat(): Rename parsers + Add `font-display` in to-css-font-import + U…
Specifyapp/parsers pull request #44
Opened 2020-12-16 15:23 UTC by ChucKN0risK

## What it does

- Rename parsers:
    - `to-css-font` => `to-css-font-import`
    - `to-css-texStyle` => `to-css-text-style`
    - `optimize-svg` => `svgo`
- Add `font-display` in to-css-font-import
- Update all parsers README content

2020-12-17 12:58 UTC, AMoreaux requested changes

2020-12-17 12:58 UTC, AMoreaux commented on parsers/camelcasify/README.md
> +| `keys`                 | false      | `Array`   | `["name"]` | The list of keys where the function will be applied                                                                        |
For me `optional` is more explicit than `false`

2020-12-17 12:58 UTC, AMoreaux commented on parsers/camelcasify/README.md
> +### Config in `.specifyrc.json`
The config file is not `.specifyrc.json` every time. It could be anything.

2020-12-17 12:58 UTC, AMoreaux commented on parsers/camelcasify/README.md
> +  "parsers": [
If you write the key `parsers` you are in the rule's context. But here it's specific parser documentation.

2020-12-17 12:58 UTC, AMoreaux commented on parsers/pick/README.md
> +        "keys": ["name"]
Why remove type?

2020-12-17 12:58 UTC, AMoreaux commented on parsers/px-to-rem/README.md
> -      ...
Why remove that?

2020-12-17 12:58 UTC, AMoreaux commented on parsers/svgo/README.md
> +Under the hood, the SVG string returned by the `url` property is the one you want to optimize:
For me, this information shouldn't be in the section "Before/After"

2020-12-17 12:58 UTC, AMoreaux commented on parsers/svgo/README.md
> +Array of object with the keys to apply pascalcase function
Why there is a reference to pascalcase?

2020-12-17 12:58 UTC, AMoreaux commented on parsers/to-css-custom-properties/README.md
> +### Before/After
Before/after should be after type section.

2020-12-17 12:58 UTC, AMoreaux commented on parsers/to-css-font-import/to-css-font-import.parser.ts
> +    if (token.value?.fontWeight) return entry + `font-weight: ${token.value.fontWeight};`;
Prefer a ternary condition to prevent unnecessary double return.

2020-12-17 12:58 UTC, AMoreaux commented on parsers/to-css-font-import/to-css-font-import.parser.ts
> +    return entry + `font-display: ${fontDisplay};`;
Prefer es6 interpolation.

2021-01-07 16:58 UTC, AllanMichay commented on parsers/convert-font/README.md
> +Array of object with the keys to apply `kebabcase` function
Why the kebabcase function if we are in the convert font ?

2021-01-07 16:58 UTC, AllanMichay commented on parsers/to-css-font-import/README.md
> +```json
Why is the input a textStyle token. We use fontToken for the font import right ?

2021-01-08 10:35 UTC, AllanMichay submitted a review, later dismissed

2021-01-08 10:37 UTC, AMoreaux approved these changes

2021-01-08 11:23 UTC, AMoreaux approved these changes

2021-01-08 11:28 UTC, merged