feat(commands): create create-parser command
Specifyapp/parsers pull request #48
Opened 2021-01-18 09:06 UTC by AllanMichay

## What it does

Add a command `yarn create-parser` to easily create a parser using a skeleton

2021-01-18 09:44 UTC, AMoreaux requested changes

2021-01-18 09:44 UTC, AMoreaux commented on create-parser.sh
> +sed -i.baku 's/parser-name-skeleton/'"$beautifiedName"'/g' "parsers/$name/README.md";
`.baku`? It's normal?

2021-01-18 09:44 UTC, AMoreaux commented on parser-skeleton/parser-skeleton.spec.ts
> +// The token type. It contains shared informations and methods.
Add more example of tests to encourage tests writing

2021-01-18 09:44 UTC, AMoreaux commented on parser-skeleton/README.md
> +# parser-name-skeleton
In `.sh` script. Which line renames this part?

2021-01-18 13:24 UTC, AMoreaux submitted a review, later dismissed

2021-01-18 13:45 UTC, AMoreaux approved these changes

2021-02-23 22:36 UTC, ChucKN0risK requested changes

2021-02-23 22:36 UTC, ChucKN0risK commented on README.md
> +Specify is a central platform for companies who want to unify their brand identity, by connecting their design system tools.
Please replace by our current baseline: "Specify helps you unify your brand identity by collecting, storing and distributing design tokens and assets — automatically."

2021-02-23 22:36 UTC, ChucKN0risK commented on README.md
> +4. Execute `yarn create-parser [PARSER NAME]`. Parser name should be in kebab-case.
Replace "kebab-case" by "kebabcase"

2021-02-23 22:36 UTC, ChucKN0risK commented on README.md
>  - A `README.md` file which contains:
Replace "which contains:" by "containing"

2021-02-23 22:36 UTC, ChucKN0risK commented on README.md
>  If you need another library to develop your parser:
Replace "If you need another library to develop your parser:" by "Need another library to develop your parser?"

2021-02-23 22:36 UTC, ChucKN0risK commented on README.md
> +To use our design tokens seed:
Replace "seed" by "seeds"

2021-02-23 22:36 UTC, ChucKN0risK commented on README.md
>  2. Use the `seeds.tokens` variable according to your needs.
Remove the period

2021-02-23 22:36 UTC, ChucKN0risK commented on create-parser.sh
> +  echo "Please name your parser (name needs to be in kebab-case)";
Replace "Please name your parser (name needs to be in kebab-case)" by "Please name your parser. It needs to be in kebabcase."

2021-02-23 22:36 UTC, ChucKN0risK commented on create-parser.sh
> +  echo "The parser $name already exist. Please choose another name.";
Replace "The parser $name already exist. Please choose another name." by "A parser with the same name already exists. Please choose another name."

2021-02-23 22:36 UTC, ChucKN0risK commented on create-parser.sh
> +echo "You can now develop your parser. Go to parsers/$name and start developing 💪"
Replace "You can now develop your parser. Go to parsers/$name and start developing 💪" by "You can now create your parser. Go to parsers/$name 💪"

2021-02-23 22:36 UTC, ChucKN0risK commented on create-parser.sh
> +echo "You can launch your tests using yarn test parsers/$name/$name.spec.ts"
Remove "You can"

2021-02-23 22:36 UTC, ChucKN0risK commented on create-parser.sh
> +echo "You can find more informations on https://specifyapp.com/developers/parsers"
Replace "You can find more informations on https://specifyapp.com/developers/parsers" by "Learn more on https://specifyapp.com/developers/parsers".

2021-04-16 12:02 UTC, closed without merging