feat(name-assets-files-by-template): add parser to add fileName prope…
Specifyapp/parsers pull request #51
Opened 2021-02-23 22:19 UTC by AMoreaux

…rty in value

## What it does

- add a parser to append `fileName` property in value that will be used to write files.

2021-02-25 13:47 UTC, AllanMichay approved these changes

2021-03-01 09:37 UTC, ChucKN0risK requested changes

2021-03-01 09:54 UTC, ChucKN0risK requested changes

2021-03-01 09:54 UTC, ChucKN0risK commented on parsers/name-assets-files-by-pattern/README.md
> +      "fileName": "bitmapExampleWithoutDimension@2x.png"
WithDimensions*

2021-03-01 09:54 UTC, ChucKN0risK commented on parsers/name-assets-files-by-pattern/README.md
> +    "name": "bitmapExampleWithoutDimension"
bitmapExampleWithDimensions*

2021-03-01 09:57 UTC, AllanMichay approved these changes

2021-03-01 10:05 UTC, ChucKN0risK approved these changes

2021-03-02 10:17 UTC, AllanMichay approved these changes

2021-03-04 13:02 UTC, merged