fix(text-styles): fix text style naming
Specifyapp/parsers pull request #62
Opened 2021-05-21 15:45 UTC by AllanMichay

## What it does

Fix text style naming : We used the Font Family instead of the token name when generating files using our text styles

## Linear ticket
Resolves DEV-853

2021-05-21 15:56 UTC, ChucKN0risK approved these changes

2021-05-24 19:50 UTC, AMoreaux commented
The case when the textStyle hasn't font is not managed.

2021-05-24 19:51 UTC, AMoreaux requested changes
The case when the textStyle hasn't font is not managed.

2021-05-26 13:00 UTC, ChucKN0risK approved these changes

2021-05-26 13:01 UTC, merged