feat(omit): add parser omit
Specifyapp/parsers pull request #80
Opened 2021-09-07 16:18 UTC by AMoreaux

## What it does

- Add parser omit

2021-09-07 16:19 UTC, ChucKN0risK requested changes
Do you have a use case in mind?

2021-09-07 16:20 UTC, AMoreaux commented
> Do you have a use case in mind?

Exclude `color` from textStyles.

2021-09-07 16:45 UTC, ChucKN0risK submitted a review, later dismissed

2021-09-10 12:37 UTC, AllanMichay commented on parsers/omit/README.md
> +    "filter"?: {
Why the `"` here?

2021-09-10 12:37 UTC, AllanMichay commented on parsers/omit/README.md
> +      "types": Array<string>
Why the `"` here?

2021-09-10 12:37 UTC, AllanMichay commented on parsers/omit/README.md
> +Array of object with the keys given in options
Array of object without the given keys

2021-09-10 12:47 UTC, AllanMichay approved these changes

2021-09-10 12:48 UTC, merged